# Generated by Django 3.0.4 on 2020-03-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0002_kyukey_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyukey',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='kyukey',
            name='tim',
        ),
    ]
