# Generated by Django 3.0.4 on 2020-03-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0003_auto_20200329_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kyukey',
            new_name='generate',
        ),
    ]
