# Generated by Django 3.0.4 on 2020-03-30 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0004_auto_20200330_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
