# Generated by Django 3.0.4 on 2020-03-30 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0005_generate_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='generate',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
