# Generated by Django 3.0.4 on 2020-03-30 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0006_auto_20200330_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
