# Generated by Django 3.0.4 on 2020-03-30 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textuten', '0007_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time',
        ),
        migrations.AlterField(
            model_name='generate',
            name='currentdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
